# Generated by Django 6.0.1 on 2026-02-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservation_party_size_gt_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
