# Generated by Django 6.0.1 on 2026-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('user', 'User'), ('admin', 'Admin')], default='guest', max_length=20),
        ),
    ]
