# Generated by Django 6.0.1 on 2026-02-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='note',
        ),
    ]
