# Generated by Django 6.0.1 on 2026-02-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_reservation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('aktivna', 'Aktivna'), ('neaktivna', 'Neaktivna')], default='aktivna', max_length=20),
        ),
    ]
